// src/app/affiliate/terms/page.tsx
import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Affiliate Terms & Conditions | YieldCraft",
  description:
    "YieldCraft Affiliate Program Terms & Conditions. Rules, commission structure, promotion standards, and enforcement policy.",
};

export default function AffiliateTermsPage() {
  return (
    <main className="min-h-screen bg-[#070A0F] text-white">
      {/* Subtle background */}
      <div className="pointer-events-none fixed inset-0 opacity-40">
        <div className="absolute inset-0 bg-[radial-gradient(900px_circle_at_20%_0%,rgba(120,119,198,0.25),transparent_55%),radial-gradient(900px_circle_at_80%_10%,rgba(56,189,248,0.18),transparent_55%),radial-gradient(900px_circle_at_50%_100%,rgba(34,197,94,0.10),transparent_60%)]" />
        <div className="absolute inset-0 bg-[linear-gradient(to_bottom,rgba(255,255,255,0.04),transparent_30%,rgba(255,255,255,0.03))]" />
      </div>

      <div className="relative mx-auto w-full max-w-4xl px-4 py-10 sm:px-6 sm:py-14">
        {/* Header */}
        <div className="mb-8 flex flex-col gap-3">
          <div className="flex items-center justify-between gap-4">
            <Link
              href="/affiliate"
              className="inline-flex items-center gap-2 text-sm text-white/70 hover:text-white transition"
            >
              <span aria-hidden>←</span> Back to Affiliate Program
            </Link>

            <span className="rounded-full border border-white/10 bg-white/5 px-3 py-1 text-xs text-white/70">
              Effective: January 2026
            </span>
          </div>

          <h1 className="text-3xl font-semibold tracking-tight sm:text-4xl">
            Affiliate Terms & Conditions
          </h1>
          <p className="max-w-2xl text-sm leading-6 text-white/70">
            These terms govern participation in the YieldCraft Affiliate Program.
            They are designed to protect the brand, protect customers, and keep
            payouts clean, automated, and drama-free.
          </p>
        </div>

        {/* Card */}
        <section className="rounded-2xl border border-white/10 bg-white/[0.03] shadow-[0_0_0_1px_rgba(255,255,255,0.03)]">
          <div className="p-6 sm:p-8">
            <div className="prose prose-invert max-w-none prose-p:text-white/80 prose-li:text-white/80 prose-headings:text-white prose-strong:text-white">
              <h2>1. Program Overview</h2>
              <p>
                The YieldCraft Affiliate Program (the “Program”) allows approved
                affiliates (“Affiliates”) to earn commissions by referring new
                paying customers to YieldCraft using approved referral links
                provided by YieldCraft.
              </p>
              <p>
                YieldCraft reserves the right to approve, reject, suspend, or
                remove any Affiliate at its sole discretion.
              </p>

              <h2>2. Commission Structure</h2>
              <ul>
                <li>
                  Affiliates earn a <strong>30% recurring commission</strong> on
                  net subscription revenue generated by customers directly
                  referred through the Affiliate’s unique referral link.
                </li>
                <li>
                  Commissions apply for the{" "}
                  <strong>lifetime of the referred customer</strong>, provided:
                  <ul>
                    <li>The customer remains active and paying, and</li>
                    <li>
                      The Affiliate remains in good standing under these Terms.
                    </li>
                  </ul>
                </li>
                <li>
                  Commissions are calculated on subscription revenue actually
                  received by YieldCraft, excluding refunds, chargebacks, taxes,
                  and third-party fees.
                </li>
              </ul>
              <p>
                YieldCraft may introduce new plans, pricing, or products.
                Commission eligibility applies only to products explicitly
                included in the Program at the time of referral.
              </p>

              <h2>3. Payouts &amp; Processing</h2>
              <ul>
                <li>
                  All commission payouts are processed{" "}
                  <strong>exclusively through Stripe</strong> or a Stripe-linked
                  system designated by YieldCraft.
                </li>
                <li>
                  YieldCraft does <strong>not</strong> manually send payments,
                  wire funds, issue checks, or process payments outside Stripe.
                </li>
                <li>
                  Payouts are typically calculated and issued monthly, subject
                  to Stripe processing timelines and minimum thresholds.
                </li>
                <li>
                  Affiliates are responsible for maintaining accurate payout,
                  identity, and tax information within Stripe.
                </li>
              </ul>
              <p>
                YieldCraft is not responsible for delays, failures, or errors
                caused by Stripe or by incorrect information provided by the
                Affiliate.
              </p>

              <h2>4. Acceptable Promotion</h2>
              <p>
                Affiliates may promote YieldCraft only in honest, transparent,
                and ethical ways.
              </p>
              <p>Allowed promotional activities include:</p>
              <ul>
                <li>Content marketing (blogs, videos, newsletters, social)</li>
                <li>Educational or informational discussions</li>
                <li>Personal recommendations based on genuine experience</li>
              </ul>
              <p>All promotions must:</p>
              <ul>
                <li>
                  Clearly represent YieldCraft as a{" "}
                  <strong>software platform</strong>, not an investment vehicle
                </li>
                <li>Avoid exaggerated, misleading, or deceptive language</li>
                <li>
                  Comply with all applicable laws, regulations, and advertising
                  standards
                </li>
              </ul>

              <h2>5. Strict Prohibitions</h2>
              <p>
                The following activities are strictly prohibited and result in
                immediate termination:
              </p>
              <ul>
                <li>Spam (email, SMS, DMs, comments, automated outreach)</li>
                <li>False, misleading, or exaggerated performance claims</li>
                <li>
                  Promising profits, guaranteed returns, or specific financial
                  outcomes
                </li>
                <li>
                  Impersonation of YieldCraft, its founders, or representatives
                </li>
                <li>Fake testimonials, reviews, or endorsements</li>
                <li>
                  Brand bidding, trademark bidding, or domain squatting related
                  to YieldCraft
                </li>
                <li>
                  Misrepresenting YieldCraft as an investment fund, broker, or
                  advisory service
                </li>
              </ul>
              <p>
                No warnings are required. Violations result in immediate removal
                from the Program.
              </p>

              <h2>6. No Guarantees / No Earnings Claims</h2>
              <p>
                YieldCraft makes <strong>no guarantees</strong> regarding
                earnings, performance, trading outcomes, conversion rates, or
                Affiliate success.
              </p>
              <p>
                Affiliates may never state or imply that YieldCraft guarantees
                profits, returns, or financial success.
              </p>

              <h2>7. Termination &amp; Enforcement</h2>
              <p>YieldCraft reserves the absolute right to:</p>
              <ul>
                <li>Suspend or terminate any Affiliate account</li>
                <li>Withhold unpaid commissions associated with violations</li>
                <li>Modify or revoke access to the Program</li>
              </ul>
              <p>
                Termination may occur at any time, for any reason, with or
                without notice, including but not limited to violations of these
                Terms.
              </p>
              <p>
                Upon termination, Affiliates must immediately stop using all
                YieldCraft branding, links, and materials.
              </p>

              <h2>8. Relationship Disclaimer</h2>
              <p>
                Affiliates are independent contractors, not employees, partners,
                agents, or representatives of YieldCraft.
              </p>
              <p>
                Nothing in these Terms creates an employment relationship, a
                partnership or joint venture, or authority to bind YieldCraft in
                any way.
              </p>

              <h2>9. Changes to These Terms</h2>
              <p>YieldCraft may update or modify these Terms at any time.</p>
              <p>
                Continued participation after changes are posted constitutes
                acceptance of the updated Terms.
              </p>

              <h2>10. Acceptance</h2>
              <p>
                By submitting an application or participating in the Program,
                you confirm that you have read, understood, and agree to comply
                with these Terms.
              </p>

              <hr />

              <p className="text-sm">
                <strong>
                  If you are not comfortable with strict rules, compliance
                  requirements, and enforcement discretion, this Program is not
                  for you.
                </strong>
              </p>
            </div>
          </div>
        </section>

        {/* Footer actions */}
        <div className="mt-8 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
          <p className="text-xs text-white/60">
            © {new Date().getFullYear()} YieldCraft. All rights reserved.
          </p>
          <div className="flex gap-3">
            <Link
              href="/affiliate"
              className="rounded-xl border border-white/10 bg-white/5 px-4 py-2 text-sm text-white/80 hover:text-white hover:bg-white/10 transition"
            >
              Back to Affiliate
            </Link>
            <Link
              href="/"
              className="rounded-xl border border-white/10 bg-white/5 px-4 py-2 text-sm text-white/80 hover:text-white hover:bg-white/10 transition"
            >
              Home
            </Link>
          </div>
        </div>
      </div>
    </main>
  );
}
