"use client";

import { useEffect, useState } from "react";

type DiagnosticSeverity =
  | "info"
  | "warning"
  | "critical";

interface AtlasDiagnostic {
  id: string;
  severity: DiagnosticSeverity;
  title: string;
  description: string;
}

interface DiagnosticsState {
  loading: boolean;
  diagnostics: AtlasDiagnostic[];
  error?: string;
}

export default function AtlasDiagnosticsPanel() {
  const [state, setState] = useState<DiagnosticsState>({
    loading: true,
    diagnostics: [],
  });

  useEffect(() => {
    async function load() {
      try {
        const response = await fetch(
          "/api/admin/atlas-operations-status",
          {
            cache: "no-store",
          }
        );

        const snapshot = await response.json();

        setState({
          loading: false,
          diagnostics:
            snapshot.diagnostics?.diagnostics ?? [],
        });
      } catch {
        setState({
          loading: false,
          diagnostics: [],
          error: "Unable to load diagnostics.",
        });
      }
    }

    load();
  }, []);

  if (state.loading) {
    return (
      <div className="rounded-xl border border-white/10 bg-slate-900 p-6">
        Loading diagnostics...
      </div>
    );
  }

  if (state.error) {
    return (
      <div className="rounded-xl border border-red-500/40 bg-slate-900 p-6 text-red-300">
        {state.error}
      </div>
    );
  }

  return (
    <div className="rounded-xl border border-white/10 bg-slate-900 p-6">
      <h2 className="text-xl font-semibold">
        Operations Diagnostics
      </h2>

      <p className="mt-2 text-sm text-slate-400">
        Read-only operational alerts generated by the
        diagnostics engine.
      </p>

      <div className="mt-6 space-y-4">
        {state.diagnostics.length === 0 ? (
          <div className="rounded-lg border border-emerald-500/30 bg-emerald-500/10 p-4 text-emerald-300">
            No diagnostics detected.
          </div>
        ) : (
          state.diagnostics.map((item) => (
            <div
              key={item.id}
              className="rounded-lg border border-white/10 bg-slate-950 p-4"
            >
              <div className="flex items-center justify-between">
                <h3 className="font-semibold">
                  {item.title}
                </h3>

                <span className="rounded bg-slate-800 px-2 py-1 text-xs uppercase">
                  {item.severity}
                </span>
              </div>

              <p className="mt-2 text-sm text-slate-400">
                {item.description}
              </p>
            </div>
          ))
        )}
      </div>
    </div>
  );
}